# ═══════════════════════════════════════════════════════════════
#  VengaiCode — Deterministic (no-AI) Django + Django REST Framework
#  ai/codegen_django.py — The Django backend codegen_deterministic
#  dispatches to. Everything is written from the db_schema SNAPSHOT
#  (via django_render), the same data the migrations are rendered from,
#  so the models and api/migrations/ always agree.
#
#  What the screens get is the same REST surface as every other
#  backend: GET/POST /api/<table>, GET/PUT/DELETE /api/<table>/<id>
#  (no trailing slash; PUT changes only the fields it sends), JSON with
#  the column names as keys, the database's constraint violations as
#  readable {"detail": ...} messages (409 duplicate, 422 broken rule),
#  and a refused delete as 409. Field validation is DRF's own
#  (400, {"field": ["message"]}), which the screens also read.
# ═══════════════════════════════════════════════════════════════

from __future__ import annotations

from app.ai import db_schema
from app.ai import django_render as dr
from app.ai.codegen_shared import GeneratedFile

# Names the generated serializers/views modules import or define.
IMPORTED_NAMES = frozenset({"CrudViewSet", "Conflict"})


def _py_str(text: str) -> str:
    return repr(str(text))


def name_problems(snapshot: dict) -> list[str]:
    """Why this schema can't be written as Django models, one per line."""
    problems = []
    for table in snapshot["tables"].values():
        for column in table["column_order"]:
            reason = dr.field_name_problem(
                column, table["columns"][column], table["columns"]
            )
            if reason:
                problems.append(f"{table['label']}.{column}: {reason}.")
    return problems


# ─── models ───
def model_file(
    sql_name: str, table: dict, tables: dict, slug: str, heading: str
) -> GeneratedFile:
    imports = dr.Imports()
    model = dr.model_name(table)
    fields = [
        f"    {dr.field_name(c, table['columns'][c])} = "
        f"{dr.field_code(c, table['columns'][c], tables, imports)}"
        for c in table["column_order"]
    ]
    constraints = dr.table_constraints(table, imports)
    indexes = dr.table_indexes(table)
    body = [
        f'"""{heading}',
        "",
        "Deterministically generated by VengaiCode from the Architecture tab (no AI",
        "call). The database table is created and changed by the migrations in",
        "api/migrations/; this class describes it to Django.",
        '"""',
        "",
        *imports.lines(migrations=False),
        "",
        "",
        f"class {model}(models.Model):",
        *fields,
        "    created_at = " + dr.CREATED_AT_FIELD,
        "    updated_at = " + dr.UPDATED_AT_FIELD,
        "",
        f"    # VENGAI:CUSTOM:{slug}_model:start",
        f"    # Add methods or properties for {model} here. A new column belongs in the",
        "    # Architecture tab instead, so a migration adds it to the database.",
        "    # This block is preserved across future regenerations.",
        f"    # VENGAI:CUSTOM:{slug}_model:end",
        "",
        "    class Meta:",
        f'        db_table = "{sql_name}"',
    ]
    if constraints:
        body += (
            ["        constraints = ["]
            + [f"            {c}," for c in constraints]
            + ["        ]"]
        )
    if indexes:
        body += (
            ["        indexes = ["]
            + [f"            {i}," for i in indexes]
            + ["        ]"]
        )
    return GeneratedFile(
        path=f"backend/api/models/{slug}.py",
        language="python",
        content="\n".join(body) + "\n",
        description=f"Deterministic Django model for {table['label']}",
    )


# ─── serializers ───
def _serializer(table: dict, tables: dict) -> list[str]:
    model = dr.model_name(table)
    declared = []
    for c in table["column_order"]:
        col = table["columns"][c]
        fk = col["fk"]
        if not fk:
            continue
        target = dr.model_name(tables[fk["table"]])
        name = dr.field_name(c, col)
        args = []
        if name != c:
            args.append(f'source="{name}"')
        args.append(f"queryset={target}.objects.all()")
        if col["nullable"]:
            args.append("allow_null=True")
        if col["nullable"] or col["default"]:
            args.append("required=False")
        if fk["column"] == "id":
            declared.append(
                f"    {c} = serializers.PrimaryKeyRelatedField({', '.join(args)})"
            )
        else:
            declared.append(
                f'    {c} = serializers.SlugRelatedField(slug_field="{fk["column"]}", {", ".join(args)})'
            )
    fields = ", ".join(
        f'"{c}"' for c in ["id", *table["column_order"], "created_at", "updated_at"]
    )
    lines = [f"class {model}Serializer(serializers.ModelSerializer):"]
    lines += declared + ([""] if declared else [])
    lines += [
        "    class Meta:",
        f"        model = {model}",
        f"        fields = [{fields}]",
    ]
    return lines


def serializers_file(snapshot: dict) -> GeneratedFile:
    tables = snapshot["tables"]
    order = [t for t in snapshot["table_order"] if t in tables]
    models = sorted({dr.model_name(tables[t]) for t in order})
    lines = [
        "# One serializer per table — deterministically generated by VengaiCode from the",
        "# Architecture tab (no AI call). Rewritten on every regeneration.",
        "",
        "from rest_framework import serializers",
        "",
        f"from api.models import {', '.join(models)}",
    ]
    for t in order:
        lines += ["", ""] + _serializer(tables[t], tables)
    return GeneratedFile(
        path="backend/api/serializers.py",
        language="python",
        content="\n".join(lines) + "\n",
        description="Deterministic DRF serializers for every database table",
    )


# ─── views + urls ───
def _restrict_message(sql_name: str, snapshot: dict) -> str:
    blockers = sorted(
        {
            other["label"]
            for other in snapshot["tables"].values()
            for col in other["columns"].values()
            if col["fk"]
            and col["fk"]["table"] == sql_name
            and col["fk"]["on_delete"] == "restrict"
        }
    )
    if blockers:
        return f"Can't delete this record: {', '.join(blockers)} still refer to it."
    return "Can't delete this record: other records still refer to it."


def views_file(snapshot: dict) -> GeneratedFile:
    tables = snapshot["tables"]
    order = [t for t in snapshot["table_order"] if t in tables]
    models = sorted({dr.model_name(tables[t]) for t in order})
    lines = [
        "# REST CRUD views for every table — deterministically generated by VengaiCode",
        "# from the Architecture tab (no AI call). Everything outside the",
        "# VENGAI:CUSTOM:extra_views block is rewritten on every regeneration.",
        "",
        "from api.crud import CrudViewSet",
        f"from api.models import {', '.join(models)}",
        f"from api.serializers import {', '.join(m + 'Serializer' for m in models)}",
    ]
    for t in order:
        model = dr.model_name(tables[t])
        lines += [
            "",
            "",
            f"class {model}ViewSet(CrudViewSet):",
            f'    queryset = {model}.objects.order_by("id")',
            f"    serializer_class = {model}Serializer",
            f"    restrict_message = {_py_str(_restrict_message(t, snapshot))}",
        ]
    lines += [
        "",
        "",
        "# VENGAI:CUSTOM:extra_views:start",
        "# Add custom, non-CRUD views here (and their routes in api/urls.py).",
        "# This block is preserved across regenerations.",
        "# VENGAI:CUSTOM:extra_views:end",
    ]
    return GeneratedFile(
        path="backend/api/views.py",
        language="python",
        content="\n".join(lines) + "\n",
        description="Deterministic CRUD viewsets for every database table",
    )


def urls_file(snapshot: dict) -> GeneratedFile:
    tables = snapshot["tables"]
    order = [t for t in snapshot["table_order"] if t in tables]
    lines = [
        "# Routes for every table — deterministically generated by VengaiCode from the",
        "# Architecture tab (no AI call). Mounted under /api/ by config/urls.py, without",
        "# trailing slashes: /api/<table> and /api/<table>/<id>, the paths the generated",
        "# screens call.",
        "",
        "from rest_framework.routers import SimpleRouter",
        "",
        "from api import views",
        "",
        "router = SimpleRouter(trailing_slash=False)",
    ]
    for t in order:
        model = dr.model_name(tables[t])
        lines.append(f'router.register("{t}", views.{model}ViewSet, basename="{t}")')
    lines += [
        "",
        "urlpatterns = router.urls",
        "",
        "# VENGAI:CUSTOM:extra_routes:start",
        "# Add routes for custom views here — this block is preserved across regenerations.",
        '# Example: urlpatterns += [path("reports/summary", views.report_summary)]',
        "# VENGAI:CUSTOM:extra_routes:end",
    ]
    return GeneratedFile(
        path="backend/api/urls.py",
        language="python",
        content="\n".join(lines) + "\n",
        description="Deterministic URL routes for every database table",
    )


# ─── shared modules ───
_CRUD_PY = '''"""What every generated viewset shares, written by VengaiCode."""

from django.db.models import ProtectedError, RestrictedError
from rest_framework import status, viewsets
from rest_framework.exceptions import APIException


class Conflict(APIException):
    status_code = status.HTTP_409_CONFLICT
    default_detail = "This change conflicts with other records."


class CrudViewSet(viewsets.ModelViewSet):
    # What a refused delete says; each viewset names the tables that block it.
    restrict_message = "Can't delete this record: other records still refer to it."

    def update(self, request, *args, **kwargs):
        # PUT changes only the fields it sends, like the other generated backends.
        kwargs["partial"] = True
        return super().update(request, *args, **kwargs)

    def perform_destroy(self, instance):
        try:
            instance.delete()
        except (ProtectedError, RestrictedError):
            raise Conflict(self.restrict_message) from None
'''

_LOOKUPS_PY = '''"""The `like` lookup the Architecture's rules use in CheckConstraints,
written by VengaiCode. It is SQL LIKE exactly as the rule means it on
every backend VengaiCode generates: % and _ are wildcards, A-Z case is
ignored (SQLite's LIKE already does; Postgres gets LOWER() on both
sides), and a backslash is an ordinary character."""

import re

from django.db import models


@models.CharField.register_lookup
@models.TextField.register_lookup
class Like(models.Lookup):
    lookup_name = "like"

    def as_sql(self, compiler, connection):
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        pattern = str(self.rhs)
        escape = ""
        if "\\\\" in pattern:
            # Postgres treats a backslash as LIKE's escape character and
            # SQLite doesn't; declaring it (and doubling each one) makes it
            # a plain backslash in both.
            rhs_params = [str(p).replace("\\\\", "\\\\\\\\") for p in rhs_params]
            escape = " ESCAPE '\\\\'"
        params = [*lhs_params, *rhs_params]
        if re.search(r"[A-Za-z]", pattern):
            return f"LOWER({lhs}) LIKE LOWER({rhs}){escape}", params
        return f"{lhs} LIKE {rhs}{escape}", params
'''


def _errors_py(constraints: list[tuple[str, int, str]]) -> str:
    """`constraints` are the (text to find, status, message) entries the
    other Python backends use — the same sentences for the same rules."""
    constraints = list(constraints)
    constraints.sort(key=lambda e: len(e[0]), reverse=True)
    entries = "\n".join(
        f"    ({_py_str(k)}, {s}, {_py_str(m)})," for k, s, m in constraints
    )
    return f'''"""Readable answers for what the database refuses, written by VengaiCode.
Configured as REST_FRAMEWORK["EXCEPTION_HANDLER"] in config/settings.py."""

import re

from django.db import IntegrityError
from rest_framework.response import Response
from rest_framework.views import exception_handler as drf_exception_handler

# What each database constraint means, so a violation comes back as a
# sentence instead of a raw database error: (text to find, status, message).
CONSTRAINTS = [
{entries}
]


def exception_handler(exc, context):
    if isinstance(exc, IntegrityError):
        text = str(exc)
        for key, status, message in CONSTRAINTS:
            if re.search(re.escape(key) + r"(?![\\w.])", text):
                return Response({{"detail": message}}, status=status)
        return Response({{"detail": f"The database refused this change: {{text}}"}}, status=409)
    return drf_exception_handler(exc, context)
'''


def backend_files(
    schema: db_schema.ResolvedSchema,
    constraints: list[tuple[str, int, str]],
    headings: dict[str, str],
) -> tuple[list[GeneratedFile], list[GeneratedFile]]:
    snapshot = db_schema.snapshot(schema)
    tables = snapshot["tables"]
    models = [
        model_file(t.sql_name, tables[t.sql_name], tables, t.slug, headings[t.sql_name])
        for t in schema.tables
    ]
    backend = [
        urls_file(snapshot),
        views_file(snapshot),
        serializers_file(snapshot),
        GeneratedFile(
            path="backend/api/crud.py",
            language="python",
            content=_CRUD_PY,
            description="Shared CRUD viewset behaviour",
        ),
        GeneratedFile(
            path="backend/api/errors.py",
            language="python",
            content=_errors_py(constraints),
            description="Turns database constraint errors into readable API answers",
        ),
        GeneratedFile(
            path="backend/api/lookups.py",
            language="python",
            content=_LOOKUPS_PY,
            description="The LIKE lookup the table rules use",
        ),
    ]
    return models, backend
