# ═══════════════════════════════════════════════════════════════
#  VengaiCode — Flyway migrations for the deterministic Spring Boot backend
#  ai/migrations_flyway.py — Renders one revision (bookkeeping, history
#  and safety rules are migrations_gen's) as a Flyway SQL migration,
#  src/main/resources/db/migration/V<n>__<slug>.sql, which Spring Boot
#  applies at startup before Hibernate validates the entities against
#  the result.
#
#  Forward only: Flyway Community has no undo, so there is no downgrade
#  script — a mistake is fixed by a newer migration (which is what
#  regenerating after an Architecture change produces anyway).
#
#  Like the other renderers: rows that already exist get the new default
#  before a column becomes required, and constraints are named exactly
#  as db_schema names them, so errors map to the same messages.
# ═══════════════════════════════════════════════════════════════

from __future__ import annotations

from app.ai import db_schema
from app.ai import spring_render as sr
from app.ai.spring_render import q


class _Steps:
    def __init__(self, old: dict, new: dict) -> None:
        self.old, self.new = old, new
        self.lines: list[str] = []
        self.deferred: list[str] = []
        self.seeds: list[str] = []
        self.created: set[str] = set()

    def insert_rows(self, t: str, table: dict, rows: list[dict]) -> list[str]:
        out = []
        columns = table["columns"]
        for row in rows:
            keys = [c for c in table["column_order"] if c in row]
            if not keys:
                out.append(f"INSERT INTO {q(t)} DEFAULT VALUES;")
                continue
            values = ", ".join(
                sr.sql_literal(
                    row[k], sr.base_column(columns[k], self.new["tables"])["type"]
                )
                for k in keys
            )
            out.append(
                f"INSERT INTO {q(t)} ({', '.join(q(k) for k in keys)}) VALUES ({values});"
            )
        return out

    def delete_rows(self, t: str, table: dict, rows: list[dict]) -> list[str]:
        # A seed row is identified by its values (except JSON); a row edited
        # since is left alone.
        out = []
        columns = table["columns"]
        for row in rows:
            keys = [
                c
                for c in table["column_order"]
                if c in row and columns[c]["type"] != "json"
            ]
            if not keys:
                out.append(
                    "-- (one seed row has no comparable values, so it is left in place)"
                )
                continue
            conditions = [
                f"{q(k)} IS NULL"
                if row[k] is None
                else f"{q(k)} = {sr.sql_literal(row[k], sr.base_column(columns[k], self.old['tables'])['type'])}"
                for k in keys
            ]
            out.append(f"DELETE FROM {q(t)} WHERE {' AND '.join(conditions)};")
        return out

    def create_table(self, t: str) -> None:
        tables = self.new["tables"]
        table = tables[t]
        parts = [f"{q('id')} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"]
        parts += [
            sr.column_sql(c, table["columns"][c], tables) for c in table["column_order"]
        ]
        parts += [
            f"{q('created_at')} TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL",
            f"{q('updated_at')} TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL",
        ]
        parts += [
            f"CONSTRAINT {q(name)} UNIQUE ({', '.join(q(c) for c in cols)})"
            for name, cols in sr.uniques(table)
        ]
        parts += [
            f"CONSTRAINT {q(name)} CHECK ({sr.check_sql(table, name)})"
            for name in table["checks"]
        ]
        for c in table["column_order"]:
            col = table["columns"][c]
            if not col["fk"]:
                continue
            target = col["fk"]["table"]
            if target == t or target in self.created or target in self.old["tables"]:
                parts.append(sr.fk_sql(c, col))
            else:  # a table created later in this migration
                self.deferred.append(f"ALTER TABLE {q(t)} ADD {sr.fk_sql(c, col)};")
        self.lines.append(f"CREATE TABLE {q(t)} (")
        self.lines += [f"    {part}," for part in parts[:-1]] + [
            f"    {parts[-1]}",
            ");",
        ]
        self.lines += [
            f"CREATE INDEX {q(name)} ON {q(t)} ({', '.join(q(c) for c in cols)});"
            for name, cols in sr.indexes(table)
        ]
        self.created.add(t)
        if table["seed_rows"]:
            self.seeds += self.insert_rows(t, table, table["seed_rows"])

    def alter_column(self, t: str, column: str, changes: dict) -> None:
        tables = self.new["tables"]
        new_col = tables[t]["columns"][column]
        base = sr.base_column(new_col, tables)
        if "type" in changes or "length" in changes:
            self.lines.append(
                f"ALTER TABLE {q(t)} ALTER COLUMN {q(column)} SET DATA TYPE {sr.sql_type(base)};"
            )
        if "default" in changes:
            default = sr.sql_default(new_col)
            self.lines.append(
                f"ALTER TABLE {q(t)} ALTER COLUMN {q(column)} "
                + (
                    f"SET DEFAULT {default};"
                    if default is not None
                    else "DROP DEFAULT;"
                )
            )
        if "nullable" in changes:
            if changes["nullable"][1] is False:
                default = sr.sql_default(new_col)
                if default is not None:
                    self.lines += [
                        f"-- Rows that already exist get the default before {column} becomes required.",
                        f"UPDATE {q(t)} SET {q(column)} = {default} WHERE {q(column)} IS NULL;",
                    ]
                self.lines.append(
                    f"ALTER TABLE {q(t)} ALTER COLUMN {q(column)} SET NOT NULL;"
                )
            else:
                self.lines.append(
                    f"ALTER TABLE {q(t)} ALTER COLUMN {q(column)} DROP NOT NULL;"
                )

    def _retype(self, t: str, column: str, wanted: str, current: str) -> None:
        if wanted != current:
            self.lines.append(
                f"ALTER TABLE {q(t)} ALTER COLUMN {q(column)} SET DATA TYPE {wanted};"
            )

    def op(self, op: dict) -> None:
        kind, t = op["op"], op["table"]
        new_t, old_t = self.new["tables"], self.old["tables"]
        if kind == "create_table":
            self.create_table(t)
        elif kind == "drop_table":
            self.lines.append(f"DROP TABLE {q(t)};")
        elif kind == "add_column":
            c = op["column"]
            # Its foreign key arrives as its own add_fk step.
            self.lines.append(
                f"ALTER TABLE {q(t)} ADD COLUMN {sr.column_sql(c, new_t[t]['columns'][c], new_t)};"
            )
        elif kind == "drop_column":
            self.lines.append(f"ALTER TABLE {q(t)} DROP COLUMN {q(op['column'])};")
        elif kind == "alter_column":
            self.alter_column(t, op["column"], op["changes"])
        elif kind == "add_unique":
            self.lines.append(
                f"ALTER TABLE {q(t)} ADD CONSTRAINT {q(op['name'])} UNIQUE ({q(op['column'])});"
            )
        elif kind in ("drop_unique", "drop_fk", "drop_check"):
            self.lines.append(f"ALTER TABLE {q(t)} DROP CONSTRAINT {q(op['name'])};")
            c = op.get("column")
            if kind == "drop_fk" and c in new_t.get(t, {}).get("columns", {}):
                # The column stays, as a plain one: back to its own type
                # (an id it pointed at was BIGINT; an integer column is INTEGER).
                self._retype(
                    t,
                    c,
                    sr.sql_type(dict(old_t[t]["columns"][c], fk=None)),
                    sr.sql_type(sr.base_column(old_t[t]["columns"][c], old_t)),
                )
        elif kind == "add_fk":
            c = op["column"]
            old_col = old_t.get(t, {}).get("columns", {}).get(c)
            if old_col is not None:
                # An existing column becoming a foreign key takes the type of
                # the column it points at (ids are BIGINT), as the entity does.
                new_col = new_t[t]["columns"][c]
                self._retype(
                    t,
                    c,
                    sr.sql_type(sr.base_column(new_col, new_t)),
                    sr.sql_type(dict(new_col, fk=None)),
                )
            self.lines.append(
                f"ALTER TABLE {q(t)} ADD {sr.fk_sql(c, new_t[t]['columns'][c])};"
            )
        elif kind == "add_check":
            self.lines.append(
                f"ALTER TABLE {q(t)} ADD CONSTRAINT {q(op['name'])} CHECK ({sr.check_sql(new_t[t], op['name'])});"
            )
        elif kind == "add_index":
            idx = new_t[t]["indexes"][op["name"]]
            cols = ", ".join(q(c) for c in idx["columns"])
            if idx["unique"]:
                self.lines.append(
                    f"ALTER TABLE {q(t)} ADD CONSTRAINT {q(op['name'])} UNIQUE ({cols});"
                )
            else:
                self.lines.append(f"CREATE INDEX {q(op['name'])} ON {q(t)} ({cols});")
        elif kind == "drop_index":
            if old_t[t]["indexes"][op["name"]]["unique"]:
                self.lines.append(
                    f"ALTER TABLE {q(t)} DROP CONSTRAINT {q(op['name'])};"
                )
            else:
                self.lines.append(f"DROP INDEX {q(op['name'])};")
        elif kind == "insert_seed":
            self.seeds += self.insert_rows(t, new_t[t], op["rows"])
        elif kind == "delete_seed":
            self.lines += self.delete_rows(t, old_t[t], op["rows"])
        else:  # pragma: no cover — diff_snapshots emits nothing else
            raise ValueError(f"Unknown migration op {kind!r}")


def filename(rev_id: str, slug: str) -> str:
    return f"backend/src/main/resources/db/migration/V{int(rev_id)}__{slug}.sql"


def render_revision(rev: dict, down_id: str | None, previous_snapshot: dict) -> str:
    steps = _Steps(previous_snapshot, rev["snapshot"])
    for op in db_schema.diff_snapshots(previous_snapshot, rev["snapshot"]):
        steps.op(op)
    title = (
        "Initial schema"
        if rev["id"] == "0001"
        else (rev.get("summary") or ["No schema changes"])[0]
    )
    header = [sr.comment(title[:1].upper() + title[1:]), ""]
    header += [f"- {sr.comment(line)}" for line in rev.get("summary") or []] or [
        "- (no schema changes)"
    ]
    if rev.get("destructive"):
        header += [
            "",
            "Permanently changes existing data (confirmed when it was generated):",
        ]
        header += [f"- {sr.comment(line)}" for line in rev["destructive"]]
    header += [
        "",
        f"Version {int(rev['id'])}"
        + (f" (after {int(down_id)})" if down_id else "")
        + f", created {sr.comment(rev.get('created_at') or '')}.",
        "Written by VengaiCode from this project's Architecture tables. Flyway applies",
        "every pending version when the app starts; it never runs one twice and has no",
        "undo — a later change arrives as a NEW migration. VengaiCode never rewrites a",
        "migration once generated, so it is safe to edit this file by hand, but Flyway",
        "refuses a file that changed after it ran (its checksum) — edit before then.",
    ]
    lines = [f"-- {line}".rstrip() for line in header] + [""]
    body = steps.lines + steps.deferred + steps.seeds
    lines += body or ["-- (no schema changes)", "SELECT 1;"]
    return "\n".join(lines) + "\n"
