# ═══════════════════════════════════════════════════════════════
#  VengaiCode — Tech Stack Compatibility Matrix
#  ai/stack_matrix.py — Lets a user pick a UI language+framework, a
#  backend language+framework, and an API style, and tells them
#  definitively whether that combination is possible.
#
#  HONEST SCOPE: "possible" is judged in two layers.
#    1. COHERENCE — does the framework actually run in that language,
#       and does the backend actually support that API style? This is
#       checked exhaustively against every known framework/language/
#       API-style combination (see ALL_COHERENT_COMBOS below) — not a
#       guess.
#    2. BUILDABILITY — of the combinations that ARE coherent, only a
#       small set (BUILDABLE_NOW) can actually be generated by
#       codegen.py today. A coherent-but-unbuilt combo is never
#       silently swapped for React+FastAPI without saying so — see
#       get_project_stack()'s "fallback_reason".
#  Whenever a request isn't buildable (or isn't even coherent), the
#  nearest BUILDABLE combination is suggested, found by scoring every
#  entry in BUILDABLE_NOW — never a heuristic guess.
# ═══════════════════════════════════════════════════════════════

# ─── Frontend (UI) side ───
FRONTEND_FRAMEWORKS: dict[str, dict] = {
    "react":            {"label": "React",                 "languages": ["javascript", "typescript"], "category": "web"},
    "vue":              {"label": "Vue",                    "languages": ["javascript", "typescript"], "category": "web"},
    "angular":          {"label": "Angular",                "languages": ["typescript"],                "category": "web"},
    "svelte":           {"label": "Svelte",                 "languages": ["javascript", "typescript"], "category": "web"},
    "html_css_js":      {"label": "Plain HTML/CSS/JS",      "languages": ["javascript"],                "category": "web"},
    "flutter":          {"label": "Flutter",                "languages": ["dart"],                      "category": "mobile"},
    "swiftui":          {"label": "SwiftUI",                "languages": ["swift"],                     "category": "mobile"},
    "jetpack_compose":  {"label": "Jetpack Compose",        "languages": ["kotlin"],                     "category": "mobile"},
    "o3de":             {"label": "Open 3D Engine (O3DE)",  "languages": ["o3de_script"],                "category": "game"},
}

# ─── Backend side ───
BACKEND_FRAMEWORKS: dict[str, dict] = {
    "fastapi":     {"label": "FastAPI",       "languages": ["python"],                    "api_styles": ["rest", "graphql"]},
    "flask":       {"label": "Flask",         "languages": ["python"],                    "api_styles": ["rest", "graphql"]},
    "django":      {"label": "Django",        "languages": ["python"],                    "api_styles": ["rest", "graphql"]},
    "express":     {"label": "Express",       "languages": ["javascript", "typescript"], "api_styles": ["rest", "graphql"]},
    "nestjs":      {"label": "NestJS",        "languages": ["typescript", "javascript"], "api_styles": ["rest", "graphql", "grpc"]},
    "spring_boot": {"label": "Spring Boot",   "languages": ["java", "kotlin"],            "api_styles": ["rest", "graphql", "grpc"]},
    "rails":       {"label": "Ruby on Rails", "languages": ["ruby"],                       "api_styles": ["rest", "graphql"]},
    "laravel":     {"label": "Laravel",       "languages": ["php"],                        "api_styles": ["rest", "graphql"]},
    "aspnet_core": {"label": "ASP.NET Core",  "languages": ["csharp"],                     "api_styles": ["rest", "graphql", "grpc"]},
    "actix":       {"label": "Actix",         "languages": ["rust"],                       "api_styles": ["rest", "graphql"]},
    "axum":        {"label": "Axum",          "languages": ["rust"],                       "api_styles": ["rest", "graphql"]},
    "gin":         {"label": "Gin",           "languages": ["go"],                         "api_styles": ["rest", "graphql"]},
    "none":        {"label": "No separate backend (O3DE project)", "languages": ["none"], "api_styles": ["none"]},
}

# Public, pickable API styles. "none" is an internal sentinel used only by
# the O3DE/"no backend" pairing — never offered as a user choice.
API_STYLES: list[str] = ["rest", "graphql", "grpc"]

# Partial-credit adjacency for the nearest-match scorer. Anything not listed
# here is its own singleton family (no partial credit against other languages).
LANGUAGE_FAMILIES: dict[str, set[str]] = {
    "javascript": {"javascript", "typescript"},
    "typescript": {"javascript", "typescript"},
    "java": {"java", "kotlin"},
    "kotlin": {"java", "kotlin"},
}

def _norm(value: str | None) -> str:
    return (value or "").strip().lower()


def _game_pairing_ok(frontend: str, backend: str, api_style: str) -> bool:
    """O3DE only ever pairs with the 'no backend' sentinel, and vice versa."""
    if frontend == "o3de" or backend == "none":
        return frontend == "o3de" and backend == "none" and api_style == "none"
    return api_style != "none"


def _tuple(selection: dict) -> tuple[str, str, str, str, str]:
    return (
        _norm(selection.get("frontend_framework")),
        _norm(selection.get("frontend_language")),
        _norm(selection.get("backend_framework")),
        _norm(selection.get("backend_language")),
        _norm(selection.get("api_style")),
    )


def _combo_from_tuple(combo: tuple[str, str, str, str, str]) -> dict:
    fe, fe_lang, be, be_lang, api = combo
    fe_meta = FRONTEND_FRAMEWORKS.get(fe, {})
    be_meta = BACKEND_FRAMEWORKS.get(be, {})
    return {
        "selection": {
            "frontend_framework": fe,
            "frontend_language": fe_lang,
            "backend_framework": be,
            "backend_language": be_lang,
            "api_style": api,
        },
        "frontend_label": fe_meta.get("label", fe),
        "backend_label": be_meta.get("label", be),
        "buildable_now": combo in BUILDABLE_NOW,
    }


def _all_coherent_combos() -> set[tuple[str, str, str, str, str]]:
    """
    Every (frontend, frontend_language, backend, backend_language, api_style)
    tuple that is internally consistent — computed once by exhaustively
    walking the matrix, not guessed. This is what "check every possibility"
    means in practice: the combinatorial space is small enough to enumerate
    outright.
    """
    combos: set[tuple[str, str, str, str, str]] = set()
    for fe, fe_meta in FRONTEND_FRAMEWORKS.items():
        for fe_lang in fe_meta["languages"]:
            for be, be_meta in BACKEND_FRAMEWORKS.items():
                for be_lang in be_meta["languages"]:
                    for api in be_meta["api_styles"]:
                        if _game_pairing_ok(fe, be, api):
                            combos.add((fe, fe_lang, be, be_lang, api))
    return combos


ALL_COHERENT_COMBOS: set[tuple[str, str, str, str, str]] = _all_coherent_combos()


def _compute_buildable_now() -> dict[tuple[str, str, str, str, str], str]:
    """
    The combinations codegen.py can actually generate today, computed from
    the frontend/backend adapter registries rather than hand-maintained —
    registering a new adapter in app.ai.codegen.frontend/backend
    immediately unlocks every combination it's coherent in, with zero
    edits needed here.

    Checking each adapter's supported_languages/supported_api_styles (not
    just "an adapter is registered for this framework") matters: without
    it, e.g. registering a react adapter that only ever emits .jsx would
    incorrectly mark the ("react","typescript",...) combo buildable too.
    """
    # Imported here, not at module load, to avoid a circular import —
    # app.ai.codegen.frontend/backend adapters live in a different
    # package but don't need to import stack_matrix themselves, so this
    # is a one-directional dependency, just deferred to first use.
    from app.ai.codegen.backend import BACKEND_ADAPTERS
    from app.ai.codegen.frontend import FRONTEND_ADAPTERS

    buildable: dict[tuple[str, str, str, str, str], str] = {}
    for combo in ALL_COHERENT_COMBOS:
        fe, fe_lang, be, be_lang, api = combo
        if fe == "o3de":
            buildable[combo] = "o3de"
            continue
        fe_adapter = FRONTEND_ADAPTERS.get(fe)
        be_adapter = BACKEND_ADAPTERS.get(be)
        if (
            fe_adapter
            and be_adapter
            and fe_lang in fe_adapter.supported_languages
            and be_lang in be_adapter.supported_languages
            and api in be_adapter.supported_api_styles
        ):
            buildable[combo] = f"{fe}__{be}__{api}"
    return buildable


BUILDABLE_NOW: dict[tuple[str, str, str, str, str], str] = _compute_buildable_now()


def _coherence_errors(selection: dict) -> list[str]:
    """Re-runs each individual compatibility rule to explain exactly what's wrong."""
    errors: list[str] = []
    fe = _norm(selection.get("frontend_framework"))
    fe_lang = _norm(selection.get("frontend_language"))
    be = _norm(selection.get("backend_framework"))
    be_lang = _norm(selection.get("backend_language"))
    api = _norm(selection.get("api_style"))

    fe_meta = FRONTEND_FRAMEWORKS.get(fe)
    be_meta = BACKEND_FRAMEWORKS.get(be)

    if fe_meta is None:
        errors.append(f"'{selection.get('frontend_framework', '')}' is not a known UI framework.")
    elif fe_lang not in fe_meta["languages"]:
        allowed = " or ".join(lang.title() for lang in fe_meta["languages"])
        errors.append(
            f"{fe_meta['label']} requires {allowed} — "
            f"'{selection.get('frontend_language', '')}' is not compatible with {fe_meta['label']}."
        )

    if be_meta is None:
        errors.append(f"'{selection.get('backend_framework', '')}' is not a known backend framework.")
    else:
        if be_lang not in be_meta["languages"]:
            allowed = " or ".join(lang.title() for lang in be_meta["languages"])
            errors.append(
                f"{be_meta['label']} requires {allowed} — "
                f"'{selection.get('backend_language', '')}' is not compatible with {be_meta['label']}."
            )
        if api not in be_meta["api_styles"]:
            allowed = ", ".join(a.upper() for a in be_meta["api_styles"] if a != "none")
            errors.append(
                f"{be_meta['label']} doesn't support '{selection.get('api_style', '')}' as an "
                f"in-process API style — it supports {allowed or 'no separate API'}."
            )

    if fe_meta is not None and be_meta is not None and not _game_pairing_ok(fe, be, api):
        errors.append(
            "Open 3D Engine (O3DE) doesn't pair with a separate web backend or API style — "
            "pick 'No separate backend' alongside O3DE, or pick a non-O3DE UI framework "
            "alongside a real backend."
        )

    return errors


def _same_family(lang_a: str, lang_b: str) -> bool:
    return lang_b in LANGUAGE_FAMILIES.get(lang_a, set())


def _score(requested: tuple[str, str, str, str, str], candidate: tuple[str, str, str, str, str]) -> float:
    """Weighted field-match similarity — see the table in the plan for the point values."""
    r_fe, r_fe_lang, r_be, r_be_lang, r_api = requested
    c_fe, c_fe_lang, c_be, c_be_lang, c_api = candidate
    score = 0.0

    if r_fe == c_fe:
        score += 3
    elif FRONTEND_FRAMEWORKS.get(r_fe, {}).get("category") == FRONTEND_FRAMEWORKS.get(c_fe, {}).get("category"):
        score += 1

    if r_fe_lang == c_fe_lang:
        score += 2
    elif _same_family(r_fe_lang, c_fe_lang):
        score += 1

    if r_be == c_be:
        score += 3
    elif r_be_lang == c_be_lang:
        score += 1

    if r_be_lang == c_be_lang:
        score += 2
    elif _same_family(r_be_lang, c_be_lang):
        score += 1

    if r_api == c_api:
        score += 1

    return score


def find_nearest(selection: dict) -> dict:
    """Brute-force scores every currently-buildable combo and returns the closest match."""
    requested = _tuple(selection)
    best = max(BUILDABLE_NOW.keys(), key=lambda candidate: _score(requested, candidate))
    return _combo_from_tuple(best)


def validate_stack(selection: dict) -> dict:
    errors = _coherence_errors(selection)
    coherent = not errors
    combo = _tuple(selection)
    buildable_now = coherent and combo in BUILDABLE_NOW

    if buildable_now:
        result_status = "ok"
        message = "This stack is valid and ready to build."
    elif coherent:
        result_status = "coherent_not_buildable"
        message = "This stack is technically valid, but VengaiCode's code generator doesn't build it yet."
    else:
        result_status = "incoherent"
        message = "This combination isn't possible."

    return {
        "status": result_status,
        "coherent": coherent,
        "buildable_now": buildable_now,
        "coherence_errors": errors,
        "message": message,
        "suggestion": None if result_status == "ok" else find_nearest(selection),
    }


# Default recommendations, exposed for stack.py's /options endpoint.
DEFAULT_WEB_COMBO = _combo_from_tuple(("react", "javascript", "fastapi", "python", "rest"))
DEFAULT_GAME_COMBO = _combo_from_tuple(("o3de", "o3de_script", "none", "none", "none"))


def _stack_result(combo: tuple[str, str, str, str, str], source: str, fallback_reason: str | None) -> dict:
    fe, fe_lang, be, be_lang, api = combo
    return {
        "frontend_framework": fe,
        "frontend_language": fe_lang,
        "backend_framework": be,
        "backend_language": be_lang,
        "api_style": api,
        # Opaque dispatch label, e.g. "react__fastapi__rest" or "o3de" —
        # confirmed unused for display anywhere in the frontend (only
        # fallback_reason is ever rendered), so its exact format is free
        # to change; codegen.py should key off frontend_framework/
        # backend_framework directly rather than parsing this string.
        "codegen_target": BUILDABLE_NOW.get(combo, f"{fe}__{be}__{api}"),
        "source": source,
        "fallback_reason": fallback_reason,
    }


def get_project_stack(project) -> dict:
    """
    The single source of truth for "what stack should codegen.py/export.py
    actually generate for this project" — replaces the separate, duplicated
    O3DE string-sniffing that used to live independently in both files.

    Returns {"frontend_framework", "frontend_language", "backend_framework",
             "backend_language", "api_style", "codegen_target",
             "source": "selected_stack"|"downgraded_selection"|
                       "legacy_o3de_detection"|"fallback_default",
             "fallback_reason": str | None}
    `fallback_reason` is populated ONLY when the user explicitly chose a
    coherent-but-not-yet-buildable stack and it had to be substituted —
    never for projects that simply never made a structured pick, so the
    codegen UI can show a banner exactly when (and only when) a real
    substitution happened.
    """
    selected = getattr(project, "selected_stack", None)
    if selected:
        combo = _tuple(selected)
        if combo in BUILDABLE_NOW:
            return _stack_result(combo, "selected_stack", None)

        nearest = find_nearest(selected)
        nearest_combo = _tuple(nearest["selection"])
        return _stack_result(
            nearest_combo,
            "downgraded_selection",
            (
                f"You picked {selected.get('frontend_framework')} + {selected.get('backend_framework')}, "
                f"which VengaiCode can't build yet — generated the nearest supported stack instead "
                f"({nearest['frontend_label']} + {nearest['backend_label']})."
            ),
        )

    architecture = (getattr(project, "architecture_data", None) or {}).get("architecture", {})
    frontend_text = (architecture.get("tech_stack", {}) or {}).get("frontend", "")
    if isinstance(frontend_text, str) and ("o3de" in frontend_text.lower() or "open 3d engine" in frontend_text.lower()):
        return _stack_result(("o3de", "o3de_script", "none", "none", "none"), "legacy_o3de_detection", None)

    return _stack_result(("react", "javascript", "fastapi", "python", "rest"), "fallback_default", None)
