# ═══════════════════════════════════════════════════════════════
#  VengaiCode — Export API Routes (Sprint 6.5 — early Export slice)
#  api/v1/export.py — Package generated code files into a downloadable ZIP
#
#  SCOPE: This is the first, minimal slice of the Export phase —
#  just zips up whatever code files exist in codegen_data so far.
#  The full Export phase (Sprint 8+) will add packaged installers
#  (.exe/.msi/.apk), documentation bundling, and licensing.
# ═══════════════════════════════════════════════════════════════

import io
import re
import logging
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.stack_matrix import get_project_stack
from app.api.v1.auth import get_current_active_user
from app.core.database import get_db
from app.core.naming import safe_filename
from app.models.project import Project
from app.models.user import User

logger = logging.getLogger("vengaicode.export")
router = APIRouter()


def build_export_filename(project_name: str, app_name: str | None = None) -> str:
    """Build a safe ZIP filename using the app name if provided."""
    base_name = (app_name or project_name or "vengaicode_project").strip()
    if not base_name:
        base_name = "vengaicode_project"
    return f"{safe_filename(base_name)}.zip"


def build_documentation_filename(project_name: str, app_name: str | None = None) -> str:
    """Build a documentation export filename."""
    base_name = (app_name or project_name or "vengaicode_project").strip()
    if not base_name:
        base_name = "vengaicode_project"
    return f"{safe_filename(base_name)}_documentation.zip"


def build_documentation_files(project: Project) -> list[tuple[str, str]]:
    """Collect generated phase documents into a downloadable documentation bundle."""
    docs: list[tuple[str, str]] = []

    def add_doc(path: str, content: str) -> None:
        docs.append((path, content))

    overview_lines = [
        f"# {project.name}",
        "",
        f"Generated by VengaiCode on {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
    ]
    if project.description:
        overview_lines.append(f"Description: {project.description}")
    if project.raw_idea:
        overview_lines.append(f"Original idea: {project.raw_idea}")
    overview_lines.extend(["", "## Documentation Summary", ""])
    add_doc("docs/overview.md", "\n".join(overview_lines))

    requirements = (project.requirements_data or {}).get("frd", {}) or {}
    if requirements:
        requirement_lines = [
            f"# Requirements Document - {project.name}",
            "",
            f"## Overview\n{requirements.get('overview', '')}",
            "",
            f"## Problem Statement\n{requirements.get('problem_statement', '')}",
            "",
            "## Key Features",
        ]
        for feature in requirements.get("key_features", []) or []:
            requirement_lines.append(f"- {feature}")
        requirement_lines.extend(["", "## Platforms"])
        for platform in requirements.get("platforms", []) or []:
            requirement_lines.append(f"- {platform}")
        add_doc("docs/requirements.md", "\n".join(requirement_lines))

    uiux = (project.uiux_data or {}).get("design", {}) or {}
    if uiux:
        uiux_lines = [
            f"# UI/UX Design - {project.name}",
            "",
            f"## Style\n{uiux.get('design_style', '')}",
            "",
            f"## Typography\n{uiux.get('typography', '')}",
            "",
            "## Screens",
        ]
        for screen in uiux.get("screens", []) or []:
            uiux_lines.append(
                f"- {screen.get('name', 'Untitled')} — {screen.get('purpose', '')}"
            )
        add_doc("docs/uiux.md", "\n".join(uiux_lines))

    architecture = (project.architecture_data or {}).get("architecture", {}) or {}
    if architecture:
        architecture_lines = [
            f"# Architecture Summary - {project.name}",
            "",
            f"## Summary\n{architecture.get('architecture_summary', '')}",
            "",
            "## Tech Stack",
        ]
        for key, value in (architecture.get("tech_stack", {}) or {}).items():
            architecture_lines.append(f"- {key}: {value}")
        add_doc("docs/architecture.md", "\n".join(architecture_lines))

    if project.codegen_data and project.codegen_data.get("codegen"):
        codegen_summary = project.codegen_data["codegen"].get("summary", "")
        add_doc(
            "docs/codegen.md",
            f"# Code Generation Summary - {project.name}\n\n{codegen_summary}",
        )

    if project.testing_data and project.testing_data.get("testing"):
        testing_summary = project.testing_data["testing"].get("summary", "")
        coverage_notes = project.testing_data["testing"].get("coverage_notes", "")
        add_doc(
            "docs/testing.md",
            f"# Testing Summary - {project.name}\n\n## Summary\n{testing_summary}\n\n## Coverage Notes\n{coverage_notes}",
        )

    if len(docs) == 1:
        add_doc(
            "docs/summary.md",
            "No documentation has been generated yet for this project.",
        )
    return docs


def _safe_zip_path(path: str) -> str:
    """A relative path that can't leave the folder the ZIP is unzipped
    into: empty, "." and ".." segments are dropped. (The old
    `lstrip("/").replace("..", "")` turned "/../etc/passwd" back into the
    absolute "/etc/passwd" — the slash reappeared once ".." was gone.)"""
    parts = re.split(r"[\\/]+", path)
    return "/".join(p for p in parts if p not in ("", ".", ".."))


def export_bundle_files(project: Project) -> list[tuple[str, str]]:
    """Everything a project's download contains, as (path, text) pairs:
    a README, the phase documents, then every generated code file. The
    one source for "Download ZIP" and the QR share options (a download
    link and the offline QR sequence), so they always hand over the same
    files. Works before code exists too — then it's the documents only."""
    codegen = (project.codegen_data or {}).get("codegen") or {}
    files = codegen.get("files", []) or []
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    if files:
        readme = (
            f"# {project.name}\n\n"
            f"Generated by VengaiCode 🐯 on {today}\n\n"
            f"{codegen.get('summary', '')}\n\n"
            f"---\n\n"
            f"⚠️  This is a STARTER SKELETON, not a finished application.\n"
            f"Files include model definitions, API route stubs, and basic\n"
            f"component shells based on your approved requirements, UI/UX\n"
            f"design, and architecture. Business logic and styling still\n"
            f"need to be implemented.\n\n"
            f"Files included: {len(files)}\n"
        )
    else:
        readme = (
            f"# {project.name}\n\n"
            f"Exported from VengaiCode 🐯 on {today}\n\n"
            "No code has been generated for this project yet — this bundle holds its documents only.\n"
        )
    bundle = [("README.md", readme), *build_documentation_files(project)]
    for file_data in files:
        bundle.append(
            (
                _safe_zip_path(file_data.get("path", "unnamed_file.txt")),
                file_data.get("content", ""),
            )
        )
    return bundle


def build_bundle_zip(bundle: list[tuple[str, str]]) -> bytes:
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for path, content in bundle:
            zip_file.writestr(path, content)
    return zip_buffer.getvalue()


def get_repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def add_template_folder_to_zip(
    zip_file: zipfile.ZipFile, template_dir: Path, prefix: str
) -> None:
    for file_path in template_dir.rglob("*"):
        if file_path.is_file():
            relative_path = file_path.relative_to(template_dir)
            zip_path = Path(prefix) / relative_path
            zip_file.writestr(str(zip_path), file_path.read_text(encoding="utf-8"))


def is_o3de_project(project: Project) -> bool:
    return get_project_stack(project)["frontend_framework"] == "o3de"


@router.get(
    "/{project_id}/download",
    summary="Download generated code files as a ZIP archive",
)
async def download_project_zip(
    project_id: str,
    include_o3de: bool = False,
    app_name: str | None = None,
    user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Packages the project's generated code files (from codegen_data)
    into a ZIP archive and streams it back for download.

    This is the first slice of the Export phase — just the raw
    generated files, preserving their folder structure. Later
    sprints will add: documentation (README, FRD, architecture docs),
    packaged installers, and licensing/Tiger stamp injection.
    """
    result = await db.execute(
        select(Project).where(
            Project.id == project_id,
            Project.user_id == user.id,
        )
    )
    project = result.scalar_one_or_none()

    if project is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Project not found."
        )

    if not project.codegen_data or not project.codegen_data.get("codegen"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No generated code available to export yet.",
        )

    files = project.codegen_data["codegen"].get("files", [])
    if not files:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No files found in generated code.",
        )

    # Build ZIP in memory — README, documents, then the code files
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for path, content in export_bundle_files(project):
            zip_file.writestr(path, content)

        # Include O3DE template if the project looks like O3DE or the
        # client explicitly requested it via the `include_o3de` query flag.
        if include_o3de or is_o3de_project(project):
            template_root = get_repo_root() / "templates" / "o3de"
            if template_root.exists():
                add_template_folder_to_zip(zip_file, template_root, "o3de_template")

    zip_buffer.seek(0)

    filename = build_export_filename(project.name, app_name)

    logger.info(f"Exported {len(files)} files for project {project_id} as {filename}")

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )


@router.get(
    "/{project_id}/documents",
    summary="Download generated documentation as a ZIP archive",
)
async def download_project_documents(
    project_id: str,
    app_name: str | None = None,
    user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Project).where(
            Project.id == project_id,
            Project.user_id == user.id,
        )
    )
    project = result.scalar_one_or_none()

    if project is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Project not found."
        )

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for path, content in build_documentation_files(project):
            zip_file.writestr(path, content)

    zip_buffer.seek(0)
    filename = build_documentation_filename(project.name, app_name)

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
