# ═══════════════════════════════════════════════════════════════
#  VengaiCode — Export API Routes (Sprint 6.5 — early Export slice)
#  api/v1/export.py — Package generated code files into a downloadable ZIP
#
#  SCOPE: This is the first, minimal slice of the Export phase —
#  just zips up whatever code files exist in codegen_data so far.
#  The full Export phase (Sprint 8+) will add packaged installers
#  (.exe/.msi/.apk), documentation bundling, and licensing.
# ═══════════════════════════════════════════════════════════════

import io
import logging
import re
import zipfile
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.v1.auth import get_current_active_user
from app.core.database import get_db
from app.models.project import Project
from app.models.user import User

logger = logging.getLogger("vengaicode.export")
router = APIRouter()


def safe_filename(name: str) -> str:
    """Sanitize project name for use as a zip filename."""
    cleaned = re.sub(r"[^\w\s-]", "", name).strip()
    cleaned = re.sub(r"[\s]+", "_", cleaned)
    return cleaned[:50] or "vengaicode_project"


@router.get(
    "/{project_id}/download",
    summary="Download generated code files as a ZIP archive",
)
async def download_project_zip(
    project_id: str,
    user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Packages the project's generated code files (from codegen_data)
    into a ZIP archive and streams it back for download.

    This is the first slice of the Export phase — just the raw
    generated files, preserving their folder structure. Later
    sprints will add: documentation (README, FRD, architecture docs),
    packaged installers, and licensing/Tiger stamp injection.
    """
    result = await db.execute(
        select(Project).where(
            Project.id == project_id,
            Project.user_id == user.id,
        )
    )
    project = result.scalar_one_or_none()

    if project is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Project not found.")

    if not project.codegen_data or not project.codegen_data.get("codegen"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No generated code available to export yet.",
        )

    files = project.codegen_data["codegen"].get("files", [])
    if not files:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No files found in generated code.",
        )

    # Build ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # Add a simple README at the root explaining what this is
        readme_content = (
            f"# {project.name}\n\n"
            f"Generated by VengaiCode 🐯 on "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}\n\n"
            f"{project.codegen_data['codegen'].get('summary', '')}\n\n"
            f"---\n\n"
            f"⚠️  This is a STARTER SKELETON, not a finished application.\n"
            f"Files include model definitions, API route stubs, and basic\n"
            f"component shells based on your approved requirements, UI/UX\n"
            f"design, and architecture. Business logic and styling still\n"
            f"need to be implemented.\n\n"
            f"Files included: {len(files)}\n"
        )
        zip_file.writestr("README.md", readme_content)

        # Add each generated file at its specified path
        for file_data in files:
            path = file_data.get("path", "unnamed_file.txt")
            content = file_data.get("content", "")
            # Prevent path traversal — strip any leading slashes or ../
            safe_path = path.lstrip("/").replace("..", "")
            zip_file.writestr(safe_path, content)

    zip_buffer.seek(0)

    filename = f"{safe_filename(project.name)}_vengaicode_export.zip"

    logger.info(f"Exported {len(files)} files for project {project_id} as {filename}")

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
