name: Backend Build Check

on:
  push:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        

      - name: Install Dependencies
        run: pnpm install

      - name: Build Backend
        run: turbo run build --filter=@vengaicode/backend