name: Build Check

on:
  push:
    branches:
      - main

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        

      - name: Install Dependencies
        run: pnpm install

      - name: Build Workspace
        run: pnpm build
